### ISSUE TITLE
Merge into libgdx

### ISSUE THREAD

**Issue by realitix** [xpenatan/gdx-bullet-gwt#1]
Hi xpenatant,
It's great what you've done !

Do you plan to merge it in the gwt backend of libgdx ?

**Comment by xpenatan** [comment]
Well I tried but it seems they dont want it. it takes days to get something into the core (even for a simple file like this https://github.com/libgdx/libgdx/pull/3729).

**Comment by intrigus** [comment]
I'm sure that they want it. But somebody has to ensure that it doesn't break code and so on. Mobidevelop maintains the gwt backend and he still has a life. I'd suggest asking him on IRC if he can merge it or have look at it. 

I know that merging PRs can take a very long time, but I've also seen other repositories where it still takes longer.

**Comment by realitix** [comment]
I'm working on openstack and indeed it's slowwwwww

**Comment by xpenatan** [comment]
Offtopic  @realitix  what is a easier way to contact you?    I managed to really see whats going on with shadow_clean branch.  There is a few issues.   Im only testing Direction light now. 

As you can see, orthographic camera (Blue lines) is not rotating (or syncing)  if I rotate my main camera (Yellow lines), as result its blocking some of my view. 
If the main camera#far is high  the shadow quality is reduced a lot and if I set it low I cant see nothing =). 

https://drive.google.com/file/d/0B7siHNeG5zjhSHFLYTlzUi1FTU0/view

I think the quality of the shadow should not depend of the main_camera#far

**Comment by realitix** [comment]
You can contact me by email, look into my commit you will see my email.

For DirectionalLight, 2 problems:
- Current default DirectionalAnalyzer is a shit ! I have to rework on it.
- Quality of shadows depends on main camera far and near and there is no other way. The problem is that your depth buffer contains value between 0-1, if far/near is high, we loose precision. The solution for a directional light is called cascade shadow mapping. I will work on that later.
  I will be on irc everyday next week I can help you with that.
